### DISCUSSION TITLE
SSO in Helm Chart

### DISCUSSION THREAD

**Discussion by ASUSPeterShen** [apache/streampark#4234] [Q&A]
StreamPark version = 2.1.5
Helm Chart version = 2.1.5

According to the [config.yaml](https://github.com/apache/streampark/blob/v2.1.5/helm/streampark/conf/config.yaml), there is no any corresponding field for SSO configuration like the original [application-sso.yml](https://streampark.apache.org/docs/platform/sso#how-to-enable-sso-login).

Following is my `config.yaml`, it does not show any SSO option on the login page.
```yaml
logging:
  level:
    root: info
server:
  port: 10000
  session:
    ttl: 2h
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256
sso:
  enable: true
  pac4j:
    callbackUrl: https://streampark.local/callback
    clientsProperties:
      oidc:
        discoveryUri: https://streampark.local/realms/example/.well-known/openid-configuration
        id: streampark
        secret: xxxx-xxxx-xxxx
        useNonce: true
```

![image](https://github.com/user-attachments/assets/e286abcd-3226-4083-a0ba-ed087c834026)

How to turn on SSO feature and insert our configuration via Helm Chart release?
