### ISSUE TITLE
[Bug] docker-compose error

### ISSUE THREAD

**Issue by bulolo** [apache/streampark#1310]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/10026498/182280547-798610e7-2177-4946-b169-6767d50bfc09.png">
<img width="1864" alt="image" src="https://user-images.githubusercontent.com/10026498/182281168-71ced5b1-a715-4947-8fb4-65d37712d5f0.png">

根据官网教程使用docker-compose 报错
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/10026498/182280591-9b42e1aa-c172-4845-87f7-5b16b9b36bf9.png">
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/10026498/182280634-ba552f70-6228-4956-b4b4-8a5f28dcf68d.png">

请问后续如何配置，以及如何解决这个问题？感谢
### StreamX Version

Version: 1.2.4 

### Flink Version

1.15.1

### Scala Version of Flink

2.12

### Error Exception

```log
根据官网 docker-compose 
http://www.streamxhub.com/zh-CN/docs/user-guide/docker-deployment
设置到第4步骤。无法进行，请问接下来要如何操作
```

### Screenshots

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/10026498/182280547-798610e7-2177-4946-b169-6767d50bfc09.png">
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/10026498/182280591-9b42e1aa-c172-4845-87f7-5b16b9b36bf9.png">
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/10026498/182280634-ba552f70-6228-4956-b4b4-8a5f28dcf68d.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
@bulolo 你可以启动一个standlone-session的flink，通过streamx的：
<img width="713" alt="图片" src="https://user-images.githubusercontent.com/60029759/182304907-0f99974f-b83b-4806-a2d4-13a6f47ead67.png">
添加这个standlone-session的集群
同时提交sql的模式选择remote (standalone)模式

**Comment by bulolo** [comment]
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/10026498/182310838-d769b5ae-484c-40d1-b6d5-e12719ef5611.png">
请问这个address该如何填写

**Comment by bulolo** [comment]
我看到 Dockerfile中

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/10026498/182334459-2151f8d0-b5d5-4df8-b451-7176fd089c21.png">

在docker中是下载了flink，意思是容器启动后，容器内会启动一个flink local cluster,是这样吗?那么对应的remote (standalone) 是指的容器内的这个local cluster吗？那么应该如何填写地址呢？
@MonsterChenzhuo

**Comment by bulolo** [comment]
@wolfboys wolfboys

**Comment by bulolo** [comment]
我感觉：是否应该 flink单独容器部署，然后才能使用remote (standalone) ? 而不是 把flink放入到容器中？
@wolfboys @MonsterChenzhuo

**Comment by bulolo** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/10026498/182754012-6aefb614-01a2-4159-af84-1ebff11bb770.png">
我看到有一个最新的更新docker-compose 文件，看到了单独起了flink容器

为了能支持多个版本，是不是应该有一个flink多版本目录比如当前的:  /streamx/flink/  对这个目录进行挂载

<img width="680" alt="image" src="https://user-images.githubusercontent.com/10026498/182754718-4c9a5a88-9622-4749-be27-61bd4721f4b4.png">

然后把flink:1.14.5容器的目录挂载出去到 /streamx/flink/flink-1.14.5目录，这样的话就支持多版本，也能从 FLINK HOME 处添加不同版本的目录位置

这样就不需要在容器内去下载flink版本
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/10026498/182754847-8d46dfdc-cd12-445c-89da-9beab8e1124d.png">

**Comment by bulolo** [comment]
当完成 Flink Home 和 Flink Cluster的配置后
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/10026498/182757794-e592304d-63b9-4244-a2f5-75f06b19fb19.png">
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/10026498/182757809-174fa583-5f0f-425c-a7d3-b74ebb603d98.png">

我已成功启动

**Comment by MonsterChenzhuo** [comment]
@bulolo “然后把flink:1.14.5容器的目录挂载出去到 /streamx/flink/flink-1.14.5目录，这样的话就支持多版本，也能从 FLINK HOME 处添加不同版本的目录位置 ” 这个想法非常nice，你有兴趣进行实现么？

**Comment by bulolo** [comment]
```

version: '3.8'
services:
  streamx-server:
    build:
      context: ../..
      dockerfile: deploy/docker/compose/Dockerfile
      args:
        DB: database
    ports:
      - 10000:10000
    depends_on:
      - database
      - jobmanager
    volumes:
      - ./flink:/streamx/flink
    restart: unless-stopped

  database:
    build:
      context: ../..
      dockerfile: deploy/docker/mysql/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: streamx
      MYSQL_USER: streamx
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"-uroot","-p123456","ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  jobmanager:
    image: flink:1.14.5-scala_2.12
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./flink/flink1.14.5:/opt/flink
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    restart: unless-stopped

  taskmanager:
    image: flink:1.14.5-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
    restart: unless-stopped

volumes:
  mysql-data:
```


<img width="1056" alt="image" src="https://user-images.githubusercontent.com/10026498/183578134-1cf89328-35b0-41e5-982a-4da24b7eea18.png">

<img width="905" alt="image" src="https://user-images.githubusercontent.com/10026498/183580017-65206d7e-fc51-4c1a-957e-9f1b7ff6fc79.png">





@MonsterChenzhuo 我简单的改下，没测过

大概就是
1./streamx/flink 挂载到 docker-compose文件同目录下的【flink文件夹】
2.将各种版本的flink容器（jobmanager）内的flink位置 挂载到 【flink文件夹】下

/flink
/flink/1.14.5    -> flink:1.14.5-scala_2.12 随时启不同的flink容器
/flink/1.15       -> flink:1.15-scala_2.12 随时启不同的flink容器

这样/streamx/flink 下就有多个版本的可挂载
