### ISSUE TITLE
[Proposal] Unify flink configuration

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#1857]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, there is no unified specification for parameter settings in the streampark project, so this time we will solve the problem of the specification of the whole parameter setting It involves setting the env environment of the job (stream env | table env), user's parameters, and user's flinksql content

before:
```
flink:
  deployment:
    property:
       ${StreamExecutionEnvironment.key} : $value
  # table
  table:
    planner: blink # (blink|old|any)
    mode: streaming #(batch|streaming)
```

after:
```
env:
  option: #cli opiton args
    target: yarn-application # yarn-application, yarn-perjob
    shutdownOnAttachedExit:
    jobmanager:
    ...
  property: 
    ${StreamExecutionEnvironment.key} : $value
    ...
    table: 
      ${TableEnvironment.key} : $value
      ...
sql: # flinksql
   my_flinksql: |
    CREATE TABLE datagen (
      f_sequence INT,
      ts AS localtimestamp,
      WATERMARK FOR ts AS ts
    ) WITH (
      ....
    );
    ...
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Hi @wolfboys , thanks for your great proposal. 

I have some questions:

1. Why do you write the sql content in the config file? As I understand, the proposal want to unify the table config, right?
2. For the table config, could we use `env.table-property` as the prefix? In other word, I don't think the `env.property.table` is a good idea. Because all configs under `env.property` will pass to Flink Env.

I use the `table.exec.mini-batch.enabled` as an example.

```
env:
  option: #cli opiton args
    target: yarn-application # yarn-application, yarn-perjob
    shutdownOnAttachedExit:
    jobmanager:
    ...
  property: 
    ${StreamExecutionEnvironment.key} : $value
    ...
  table-property: 
    table.exec.mini-batch.enabled : true
```

**Comment by wolfboys** [comment]
hi @1996fanrui :

table config definition in `env.property.table`, `env.property` will pass to Flink Env(Exclude `table` prefix), e.g:

```
env:
  property: 
    ${key1} : ${value2}
    table: 
      ${key2} : ${value2}
```
${key1} is Flink Env config, key2 is  Flink table config, not Flink Env config,  All configurations with the `env.property.table` prefix are Flink table config


use the table.exec.mini-batch.enabled as an example:

```
env:
  option: #cli opiton args
    target: yarn-application # yarn-application, yarn-perjob
    shutdownOnAttachedExit:
    jobmanager:
  property: 
    taskmanager.numberOfTaskSlots: 1
    parallelism.default: 2
    table: 
     exec.mini-batch.enabled : true

```
