### ISSUE TITLE
[Enhancement] Flink on K8s，Submit a jar job in Custom Code Mode using the -Dkubernetes.pod-template-file.jobmanage parameter 

### ISSUE THREAD

**Issue by xinzhuxiansheng** [apache/streampark#626]
## Enhancement

Currently, StreamX submits a jar function for Custom Code on K8s, which needs to be packaged and submitted again. This process is complicated and time-consuming, and the usage of pod template parameters is inconsistent with Flink's native processing. 

The following is the realization of the idea to optimize:
In Custom Code Mode, a switch can be added to submit jobs using the default -Dkubernetes.pod-template-file.jobmanage parameter. 
<img width="601" alt="图片" src="https://user-images.githubusercontent.com/7881241/149645775-1ccb40ab-c803-4766-ab39-18557693e3e6.png">

Use wget of 'initContainers' to download the application jar package and deploy the job 

The content of pod-template.yaml is as follows: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: jobmanager-pod-template
spec:
  initContainers:
    - name: flink
      image: flink:1.14.2-scala_2.11-java8
      # Use wget or other tools to get user jars from remote storage
      command: [ 'wget', 'http://xxxxxx/api/v1/file/downloadJar?fileName=flink-demo-1.0.1-SNAPSHOT-1642065346071.jar', '-O', '/opt/flink/usrlib/flink-demo-1.0.1-SNAPSHOT.jar' ]
      volumeMounts:
        - mountPath: /opt/flink/usrlib
          name: flink-artifact
  containers:
    # Do not change the main container name
    - name: flink-main-container
      resources:
        requests:
          ephemeral-storage: 2048Mi
        limits:
          ephemeral-storage: 2048Mi
      volumeMounts:
        - mountPath: /opt/flink/volumes/hostpath
          name: flink-volume-hostpath
        - mountPath: /opt/flink/usrlib
          name: flink-artifact
        - mountPath: /opt/flink/log
          name: flink-logs
      # Use sidecar container to push logs to remote storage or do some other debugging things
    #- name: sidecar-log-collector
    #  image: sidecar-log-collector:latest
    #  command: [ 'command-to-upload', '/remote/path/of/flink-logs/' ]
    #  volumeMounts:
    #    - mountPath: /flink-logs
    #      name: flink-logs
  volumes:
    - name: flink-volume-hostpath
      hostPath:
        path: /tmp
        type: Directory
    - name: flink-artifact
      emptyDir: { }
    - name: flink-logs
      emptyDir: { }
```

目前，StreamX针对Flink on k8s的Custom Code提交jar作业，需要打包镜像，再提交，这个过程复杂且耗时，且pod template参数用法与Flink原生处理不一致。
以下是想优化的思路实现:
在Custom Code Mode，可以增加一个开关，使用默认的-Dkubernetes.pod-template-file.jobmanage参数提交作业。

<img width="601" alt="图片" src="https://user-images.githubusercontent.com/7881241/149645775-1ccb40ab-c803-4766-ab39-18557693e3e6.png">

使用‘initContainers’ 的wget 下载应用jar包，部署作业

pod-template.yaml 内容如下：
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: jobmanager-pod-template
spec:
  initContainers:
    - name: flink
      image: flink:1.14.2-scala_2.11-java8
      # Use wget or other tools to get user jars from remote storage
      command: [ 'wget', 'http://xxxxxx/api/v1/file/downloadJar?fileName=flink-demo-1.0.1-SNAPSHOT-1642065346071.jar', '-O', '/opt/flink/usrlib/flink-demo-1.0.1-SNAPSHOT.jar' ]
      volumeMounts:
        - mountPath: /opt/flink/usrlib
          name: flink-artifact
  containers:
    # Do not change the main container name
    - name: flink-main-container
      resources:
        requests:
          ephemeral-storage: 2048Mi
        limits:
          ephemeral-storage: 2048Mi
      volumeMounts:
        - mountPath: /opt/flink/volumes/hostpath
          name: flink-volume-hostpath
        - mountPath: /opt/flink/usrlib
          name: flink-artifact
        - mountPath: /opt/flink/log
          name: flink-logs
      # Use sidecar container to push logs to remote storage or do some other debugging things
    #- name: sidecar-log-collector
    #  image: sidecar-log-collector:latest
    #  command: [ 'command-to-upload', '/remote/path/of/flink-logs/' ]
    #  volumeMounts:
    #    - mountPath: /flink-logs
    #      name: flink-logs
  volumes:
    - name: flink-volume-hostpath
      hostPath:
        path: /tmp
        type: Directory
    - name: flink-artifact
      emptyDir: { }
    - name: flink-logs
      emptyDir: { }
```
